// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAbrEYD5j4DDLyEDPXEXcofvClMTz1QEo',
    appId: '1:758019240650:web:8edda8c649ed769c7cfa33',
    messagingSenderId: '758019240650',
    projectId: 'proyecto2u',
    authDomain: 'proyecto2u.firebaseapp.com',
    storageBucket: 'proyecto2u.firebasestorage.app',
    measurementId: 'G-4FZV0RYPHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLc3QHkxFZ_NuzzrE69EMfbfbuHHTee-A',
    appId: '1:758019240650:android:679ddea1d4e0ca347cfa33',
    messagingSenderId: '758019240650',
    projectId: 'proyecto2u',
    storageBucket: 'proyecto2u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgP_k9kkmvlV1n89xWxfW7eq7qzTKuAOU',
    appId: '1:758019240650:ios:8ef907ddb886f9067cfa33',
    messagingSenderId: '758019240650',
    projectId: 'proyecto2u',
    storageBucket: 'proyecto2u.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgP_k9kkmvlV1n89xWxfW7eq7qzTKuAOU',
    appId: '1:758019240650:ios:8ef907ddb886f9067cfa33',
    messagingSenderId: '758019240650',
    projectId: 'proyecto2u',
    storageBucket: 'proyecto2u.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAbrEYD5j4DDLyEDPXEXcofvClMTz1QEo',
    appId: '1:758019240650:web:09d61f52c31654347cfa33',
    messagingSenderId: '758019240650',
    projectId: 'proyecto2u',
    authDomain: 'proyecto2u.firebaseapp.com',
    storageBucket: 'proyecto2u.firebasestorage.app',
    measurementId: 'G-5Z33L5BSQT',
  );
}
